### ISSUE TITLE
Login to gmail using Oauth

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/aurora-platform#2]
I was trying to authenticate users to login to the webmail using their gmail accounts . I followed the instructions [here](https://afterlogic.com/docs/webmail-lite-8/external-services/external-services-auth) And i have successfully logged in .

The problem is this message in the following image appeared to me and i was expected that the webmail will grab all inbox and the other staff from the logged in mail user . Any solution for this ?
![image](https://user-images.githubusercontent.com/8146379/35278275-263417de-0052-11e8-8c0b-893d735abacd.png)

**Comment by sash04ek** [comment]
Google auth serves a different purpose: the ability to log in webmail without entering your mail account creds each time. I.e. you log in webmail with Google, then go to settings and configure your mail account (and this mail account has nothing to do with your Google account, they are unrelated). The mail account you configure can be Gmail as well (so it can be the same as your Google account) but for webmail it will be just a mail account, there is no correlation with OAuth2 account you're using for authentication. The same way it works for Dropbox (which does not provide email at all, for instance). Mail is one thing, OAuth2 is another.

**Comment by abdelrahmanahmed** [comment]
@sash04ek so according to the provided image , password field it not related to my email password?

All i want to to do is :  
I have admin users for my system , a user logged in to my system .I want to use his email to login to webmail without letting him to enter his gmail account credentials  (and i thought it will be done with Oauth) and grab all his inbox and emails automatically

**Comment by afterlogic-support** [comment]
OAuth is used as additional login method, but it's not used as email authentication, entering GMail is still required. In other words, the product offers OAuth support for Google - but not for Gmail.

**Comment by sash04ek** [comment]
@abdelrahmanahmed, this is a password of your mail account.
 
If a user logs in webmail with OAuth and adds his mail account with a login and password, he can log into the system with OAuth and access his mailbox.
