### ISSUE TITLE
Aurora Files not accepting https.

### ISSUE THREAD

**Issue by ziyaul121** [afterlogic/aurora-platform#3]
Hi,

I have installed and configured Aurora files in centos 7 with Apache and Mysql and it is working fine with http (http://server-IP/aurora/data/aurora-files-latest/)but whenever I tried with Https https://Server-IP/aurora/data/aurora-files-latest/  than an error page coming "This site can’t be reached" ERR_CONNECTION_REFUSED

Even I have enable automatic redirect from http to https, set RedirectToHttps to true in data/settings/config.json file.

Please help me to fix out the issue. Thank a lot.

**Comment by afterlogic-support** [comment]
Hello,

From your message, it's not clear - do you actually have HTTPS configured on Apache? Setting up redirect to HTTPS on Aurora Files isn't enough, you need to setup Apache for SSL support as well, using [these guidelines](https://www.digicert.com/csr-ssl-installation/apache-openssl.htm) for instance.

**Comment by ziyaul121** [comment]
Appreciate your help. Now it works fine.

**Comment by ziyaul121** [comment]
But now Aurora file sync stop working giving error "The connection failed. The remote certificate is invalid according to the validation procedure.   "

But I have added and installed this certificate to "Trusted Root Certification Authorities" in the local computer. 

Please help me .

**Comment by afterlogic-support** [comment]
It might take several hours for SSL certificate propagation.

**Comment by ziyaul121** [comment]
Ok, Got it . But why this below error comes when I tried to access dav.php. Which plugin I need to install. Please help.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
<s:message>
There was no plugin in the system that was willing to handle this GET method. Enable the Browser plugin to get a better result here.
</s:message>
<s:file>
/var/www/aurora/data/aurora-files-latest/vendor/sabre/dav/lib/DAV/Server.php
</s:file>
<s:line>467</s:line>
<s:code>0</s:code>
<s:stacktrace>
#0 /var/www/aurora/data/aurora-files-latest/vendor/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #1 /var/www/aurora/data/aurora-files-latest/dav.php(34): Sabre\DAV\Server->exec() #2 {main}
</s:stacktrace>
</d:error>

**Comment by afterlogic-support** [comment]
Indeed, by default DAV access via web browser isn't enabled. To activate it, set **UseBrowserPlugin** to **true** in `data/settings/modules/Dav.config.json` file.

**Comment by ziyaul121** [comment]
Thanks a lot. 

But still Aurora file sync not working. How long it take while SSL certificate propagation. It is more than two days.
Pls find the attached error.
![image](https://user-images.githubusercontent.com/37359588/43672446-295511ca-97bf-11e8-8801-6b7a67c7990f.png)

**Comment by ziyaul121** [comment]
Hi, 
Can you please help me to fix out the above commented issue.

Thanks ,

**Comment by afterlogic-support** [comment]
Hi,

Can't help you without any details (server name is hidden, etc).

**Comment by ziyaul121** [comment]
Thanks a lot, I got your point and change https://IP/ to Hostname https://Hostname and issue has been resolved.

But why with IP connection failed error comes.?

**Comment by afterlogic-support** [comment]
Oh, your hidden string was an IP address, not a domain name? Obviously, SSL certificate is issued to a domain. How do you expect the client to verify the host domain name (that it matches the domain name in the cert) if you never supply that domain when connecting? SSL certs can only work if you connect via a domain name.

**Comment by ziyaul121** [comment]
Wow got it , Thanks a lot.

**Comment by ziyaul121** [comment]
Hi,
could you please guide me how I can change the "Power by Afterlogic Aurora Files." ?

![image](https://user-images.githubusercontent.com/37359588/43820183-90756ec4-9af6-11e8-855e-1822eeac82ee.png)

**Comment by afterlogic-support** [comment]
Hi, it's BottomInfoHtmlText setting in data\settings\modules\StandardLoginFormWebclient.config.json file.

**Comment by afterlogic-support** [comment]
More info at:  https://afterlogic.com/docs/aurora-corporate-8/configuring-webmail/advanced-configuration

**Comment by ziyaul121** [comment]
Thanks a lot.

**Comment by ziyaul121** [comment]
Hi,
is there any option available to restrict user access  in CORPORATE folder.?  Let say we have a folder XX in CORPORATE folder and we want to restrict access for some users. is it feasible ?

**Comment by afterlogic-support** [comment]
No, Aurora Files has no permission system.
