### ISSUE TITLE
Debian package shouldn't require Apache

### ISSUE THREAD

**Issue by Daniel15** [afterlogic/aurora-platform#4]
Hi!

The page at https://afterlogic.com/docs/webmail-lite-8/installation/installing-on-debian-ubuntu-linux said to leave feedback here.

When I try to install the Debian package, it wants to install Apache, even though I already have Nginx installed. Most other Debian packages that install PHP apps will allow either Apache, Nginx or Lighttpd to be used, and correctly configure the relevant server.

**Comment by afterlogic-support** [comment]
Currently, only Apache is supported. In the future, we'll consider adding support for other webservers. Thanks.

**Comment by afterlogic-support** [comment]
Just to clarify: the product itself can work on a variety of webservers, including Nginx of course. But this particular installation method only works with Apache at the moment. You can still install the product on other webservers using [standard installation method](https://afterlogic.com/docs/webmail-lite-8/installation/installation-instructions).
If you'd like to have Nginx support added for Debian/Ubuntu packages, please feel free to post a vote at:
https://afterlogic.uservoice.com/forums/932335-webmail-pro
(it's the same installer for WebMail Lite and Pro, so you can use either of the two sections there)
